// Customer Actions
export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAILURE = "CREATE_CUSTOMER_FAILURE";

export const GET_ALL_CUSTOMERS_REQUEST = "GET_ALL_CUSTOMERS_REQUEST";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAILURE = "GET_ALL_CUSTOMERS_FAILURE";

export const GET_CUSTOMER_BY_ID_REQUEST = "GET_CUSTOMER_BY_ID_REQUEST";
export const GET_CUSTOMER_BY_ID_SUCCESS = "GET_CUSTOMER_BY_ID_SUCCESS";
export const GET_CUSTOMER_BY_ID_FAILURE = "GET_CUSTOMER_BY_ID_FAILURE";

export const GET_CUSTOMER_BY_ID_NUM_REQUEST = "GET_CUSTOMER_BY_ID_NUM_REQUEST";
export const GET_CUSTOMER_BY_ID_NUM_SUCCESS = "GET_CUSTOMER_BY_ID_NUM_SUCCESS";
export const GET_CUSTOMER_BY_ID_NUM_FAILURE = "GET_CUSTOMER_BY_ID_NUM_FAILURE";

export const GET_RECOMMENDED_PRODUCTS_REQUEST = "GET_RECOMMENDED_PRODUCTS_REQUEST";
export const GET_RECOMMENDED_PRODUCTS_SUCCESS = "GET_RECOMMENDED_PRODUCTS_SUCCESS";
export const GET_RECOMMENDED_PRODUCTS_FAILURE = "GET_RECOMMENDED_PRODUCTS_FAILURE";

export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";