
export const GET_ALL_MEDICINES_REQUEST = "GET_ALL_MEDICINES_REQUEST";
export const GET_ALL_MEDICINES_SUCCESS = "GET_ALL_MEDICINES_SUCCESS";
export const GET_ALL_MEDICINES_FAILURE = "GET_ALL_MEDICINES_FAILURE";

export const GET_MEDICINE_BY_ID_REQUEST = "GET_MEDICINE_BY_ID_REQUEST";
export const GET_MEDICINE_BY_ID_SUCCESS = "GET_MEDICINE_BY_ID_SUCCESS";
export const GET_MEDICINE_BY_ID_FAILURE = "GET_MEDICINE_BY_ID_FAILURE";

export const GET_MEDICINES_BY_SKIN_TYPE_REQUEST = "GET_MEDICINES_BY_SKIN_TYPE_REQUEST";
export const GET_MEDICINES_BY_SKIN_TYPE_SUCCESS = "GET_MEDICINES_BY_SKIN_TYPE_SUCCESS";
export const GET_MEDICINES_BY_SKIN_TYPE_FAILURE = "GET_MEDICINES_BY_SKIN_TYPE_FAILURE";

export const SEARCH_MEDICINES_REQUEST = "SEARCH_MEDICINES_REQUEST";
export const SEARCH_MEDICINES_SUCCESS = "SEARCH_MEDICINES_SUCCESS";
export const SEARCH_MEDICINES_FAILURE = "SEARCH_MEDICINES_FAILURE";

export const CREATE_MEDICINE_REQUEST = "CREATE_MEDICINE_REQUEST";
export const CREATE_MEDICINE_SUCCESS = "CREATE_MEDICINE_SUCCESS";
export const CREATE_MEDICINE_FAILURE = "CREATE_MEDICINE_FAILURE";

export const UPDATE_MEDICINE_REQUEST = "UPDATE_MEDICINE_REQUEST";
export const UPDATE_MEDICINE_SUCCESS = "UPDATE_MEDICINE_SUCCESS";
export const UPDATE_MEDICINE_FAILURE = "UPDATE_MEDICINE_FAILURE";

export const DELETE_MEDICINE_REQUEST = "DELETE_MEDICINE_REQUEST";
export const DELETE_MEDICINE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_FAILURE = "DELETE_MEDICINE_FAILURE";